//
//  FilterTypeDelclare.m
//  FilterGenerator
//
//  Created by masaaki goshima on 2013/12/10.
//  Copyright (c) 2013年 masaaki goshima. All rights reserved.
//

#import "FilterTypeDelclare.h"

FilterInformation filterDeclare[] = {
    {GPUIMAGE_SATURATION,                 "SATURATION",                  false, NULL},
    {GPUIMAGE_CONTRAST,                   "CONTRAST",                    false, NULL},
    {GPUIMAGE_BRIGHTNESS,                 "BRIGHTNESS",                  false, NULL},
    {GPUIMAGE_LEVELS,                     "LEVELS",                      false, NULL},
    {GPUIMAGE_EXPOSURE,                   "EXPOSURE",                    false, NULL},
    {GPUIMAGE_RGB,                        "RGB",                         false, NULL},
    {GPUIMAGE_HUE,                        "HUE",                         false, NULL},
    {GPUIMAGE_WHITEBALANCE,               "WHITEBALANCE",                false, NULL},
    {GPUIMAGE_MONOCHROME,                 "MONOCHROME",                  false, NULL},
    {GPUIMAGE_FALSECOLOR,                 "FALSECOLOR",                  false, NULL},
    {GPUIMAGE_SHARPEN,                    "SHARPEN",                     false, NULL},
    {GPUIMAGE_UNSHARPMASK,                "UNSHARPMASK",                 false, NULL},
    {GPUIMAGE_TRANSFORM,                  "TRANSFORM",                   false, NULL},
    {GPUIMAGE_TRANSFORM3D,                "TRANSFORM3D",                 false, NULL},
    {GPUIMAGE_CROP,                       "CROP",                        false, NULL},
	{GPUIMAGE_MASK,                       "MASK",                        false, NULL},
    {GPUIMAGE_GAMMA,                      "GAMMA",                       false, NULL},
    {GPUIMAGE_TONECURVE,                  "TONECURVE",                   false, NULL},
    {GPUIMAGE_HIGHLIGHTSHADOW,            "HIGHLIGHT SHADOW",            false, NULL},
    {GPUIMAGE_HAZE,                       "HAZE",                        false, NULL},
    {GPUIMAGE_SEPIA,                      "SEPIA",                       false, NULL},
    {GPUIMAGE_AMATORKA,                   "AMATORKA",                    false, NULL},
    {GPUIMAGE_MISSETIKATE,                "MISSETIAKTE",                 false, NULL},
    {GPUIMAGE_SOFTELEGANCE,               "SOFT ELEGANCE",               false, NULL},
    {GPUIMAGE_COLORINVERT,                "COLOR INVERT",                false, NULL},
    {GPUIMAGE_GRAYSCALE,                  "GRAY SCALE",                  false, NULL},
    {GPUIMAGE_HISTOGRAM,                  "HISTOGRAM",                   false, NULL},
    {GPUIMAGE_AVERAGECOLOR,               "AVERAGE COLOR",               false, NULL},
    {GPUIMAGE_LUMINOSITY,                 "LUMINOSITY",                  false, NULL},
    {GPUIMAGE_THRESHOLD,                  "THRESHOLD",                   false, NULL},
    {GPUIMAGE_ADAPTIVETHRESHOLD,          "ADAPTIVE THRESHOLD",          false, NULL},
    {GPUIMAGE_AVERAGELUMINANCETHRESHOLD,  "AVERAGE LUMINANCE THRESHOLD", false, NULL},
    {GPUIMAGE_PIXELLATE,                  "PIXELLATE",                   false, NULL},
    {GPUIMAGE_POLARPIXELLATE,             "POLARPIXELLATE",              false, NULL},
    {GPUIMAGE_PIXELLATE_POSITION,         "PIXELLATE POSITION",          false, NULL},
    {GPUIMAGE_POLKADOT,                   "POLKADOT",                    false, NULL},
    {GPUIMAGE_HALFTONE,                   "HALF TONE",                   false, NULL},
    {GPUIMAGE_CROSSHATCH,                 "CROSS HATCH",                 false, NULL},
    {GPUIMAGE_SOBELEDGEDETECTION,         "SOBEL EDGE DETECTION",        false, NULL},
    {GPUIMAGE_PREWITTEDGEDETECTION,       "PREWITT EDGE DETECTION",      false, NULL},
    {GPUIMAGE_CANNYEDGEDETECTION,         "CANNY EDGE DETECTION",        false, NULL},
    {GPUIMAGE_THRESHOLDEDGEDETECTION,     "THRESHOLD EDGE DETECTION",    false, NULL},
    {GPUIMAGE_XYGRADIENT,                 "XY GRADIENT",                 false, NULL},
    {GPUIMAGE_HARRISCORNERDETECTION,      "HARRIS CORNER DETECTION",     false, NULL},
    {GPUIMAGE_NOBLECORNERDETECTION,       "NOBLE CORNER DETECTION",      false, NULL},
    {GPUIMAGE_SHITOMASIFEATUREDETECTION,  "SHITOMASIFEATURE DETECTION",  false, NULL},
    {GPUIMAGE_HOUGHTRANSFORMLINEDETECTOR, "HOUGHTRANSFORMLINEDETECTOR",  false, NULL},
    {GPUIMAGE_BUFFER,                     "BUFFER",                      false, NULL},
    {GPUIMAGE_LOWPASS,                    "LOWPASS",                     false, NULL},
    {GPUIMAGE_HIGHPASS,                   "HIGHPASS",                    false, NULL},
    {GPUIMAGE_MOTIONDETECTOR,             "MOTION DETECTOR",             false, NULL},
    {GPUIMAGE_SKETCH,                     "SKETCH",                      false, NULL},
    {GPUIMAGE_THRESHOLDSKETCH,            "THRESHOLD SKETCH",            false, NULL},
    {GPUIMAGE_TOON,                       "TOON",                        false, NULL},
    {GPUIMAGE_SMOOTHTOON,                 "SMOOTH TOON",                 false, NULL},
    {GPUIMAGE_TILTSHIFT,                  "TILT SHIFT",                  false, NULL},
    {GPUIMAGE_CGA,                        "CGA",                         false, NULL},
    {GPUIMAGE_POSTERIZE,                  "POSTERIZE",                   false, NULL},
    {GPUIMAGE_CONVOLUTION,                "CONVOLUTION",                 false, NULL},
    {GPUIMAGE_EMBOSS,                     "EMBOSS",                      false, NULL},
    {GPUIMAGE_LAPLACIAN,                  "LAPLACIAN",                   false, NULL},
    {GPUIMAGE_CHROMAKEYNONBLEND,          "CHROMAKEY NON BLEND",         false, NULL},
    {GPUIMAGE_KUWAHARA,                   "KUWAHARA",                    false, NULL},
    {GPUIMAGE_KUWAHARARADIUS3,            "KUWAHARA RADIUS3",            false, NULL},
    {GPUIMAGE_VIGNETTE,                   "VIGNETTE",                    false, NULL},
    {GPUIMAGE_GAUSSIAN,                   "GAUSSIAN",                    false, NULL},
    {GPUIMAGE_GAUSSIAN_SELECTIVE,         "GAUSSIAN SELECTIVE",          false, NULL},
    {GPUIMAGE_GAUSSIAN_POSITION,          "GAUSSIAN POSITION",           false, NULL},
    {GPUIMAGE_FASTBLUR,                   "FAST BLUR",                   false, NULL},
    {GPUIMAGE_BOXBLUR,                    "BOX BLUR",                    false, NULL},
    {GPUIMAGE_MEDIAN,                     "MEDIAN",                      false, NULL},
    {GPUIMAGE_BILATERAL,                  "BILATERNAL",                  false, NULL},
    {GPUIMAGE_MOTIONBLUR,                 "MOTION BLUR",                 false, NULL},
    {GPUIMAGE_ZOOMBLUR,                   "ZOOM BLUR",                   false, NULL},
    {GPUIMAGE_SWIRL,                      "SWIRL",                       false, NULL},
    {GPUIMAGE_BULGE,                      "BULGE",                       false, NULL},
    {GPUIMAGE_PINCH,                      "PINCH",                       false, NULL},
    {GPUIMAGE_SPHEREREFRACTION,           "SPHERE REFRACTION",           false, NULL},
    {GPUIMAGE_GLASSSPHERE,                "GLASS SPHERE",                false, NULL},
    {GPUIMAGE_STRETCH,                    "STRETCH",                     false, NULL},
    {GPUIMAGE_DILATION,                   "DILATION",                    false, NULL},
    {GPUIMAGE_EROSION,                    "EROSION",                     false, NULL},
    {GPUIMAGE_OPENING,                    "OPENING",                     false, NULL},
    {GPUIMAGE_CLOSING,                    "CLOSING",                     false, NULL},
    {GPUIMAGE_PERLINNOISE,                "PERLINNOISE",                 false, NULL},
    {GPUIMAGE_VORONOI,                    "VORONOI",                     false, NULL},
    {GPUIMAGE_MOSAIC,                     "MOSAIC",                      false, NULL},
    {GPUIMAGE_LOCALBINARYPATTERN,         "LOCAL BINARY PATTERN",        false, NULL},
    {GPUIMAGE_DISSOLVE,                   "DISSOLVE",                    false, NULL},
    {GPUIMAGE_CHROMAKEY,                  "CHROMAKEY",                   false, NULL},
    {GPUIMAGE_ADD,                        "ADD",                         false, NULL},
    {GPUIMAGE_DIVIDE,                     "DIVIDE",                      false, NULL},
    {GPUIMAGE_MULTIPLY,                   "MULTIPLY",                    false, NULL},
    {GPUIMAGE_OVERLAY,                    "OVERLAY",                     false, NULL},
    {GPUIMAGE_LIGHTEN,                    "LIGHTEN",                     false, NULL},
    {GPUIMAGE_DARKEN,                     "DARKEN",                      false, NULL},
    {GPUIMAGE_COLORBURN,                  "COLOR BURN",                  false, NULL},
    {GPUIMAGE_COLORDODGE,                 "COLOR DODGE",                 false, NULL},
    {GPUIMAGE_LINEARBURN,                 "LINEAR BURN",                 false, NULL},
    {GPUIMAGE_SCREENBLEND,                "SCREEN BLEND",                false, NULL},
    {GPUIMAGE_DIFFERENCEBLEND,            "DIFFERENCE BLEND",            false, NULL},
	{GPUIMAGE_SUBTRACTBLEND,              "SUBTRACT BLEND",              false, NULL},
    {GPUIMAGE_EXCLUSIONBLEND,             "EXCLUSION BLEND",             false, NULL},
    {GPUIMAGE_HARDLIGHTBLEND,             "HARD LIGHT BLEND",            false, NULL},
    {GPUIMAGE_SOFTLIGHTBLEND,             "SOFT LIGHT BLEND",            false, NULL},
    {GPUIMAGE_COLORBLEND,                 "COLOR BLEND",                 false, NULL},
    {GPUIMAGE_HUEBLEND,                   "HUE BLEND",                   false, NULL},
    {GPUIMAGE_SATURATIONBLEND,            "SATURATION BLEND",            false, NULL},
    {GPUIMAGE_LUMINOSITYBLEND,            "LUMINOSITY BLEND",            false, NULL},
    {GPUIMAGE_NORMALBLEND,                "NORMAL BLEND",                false, NULL},
    {GPUIMAGE_POISSONBLEND,               "POISSON BLEND",               false, NULL},
    {GPUIMAGE_OPACITY,                    "OPACITY",                     false, NULL},
    {GPUIMAGE_CUSTOM,                     "CUSTOM",                      false, NULL},
    {GPUIMAGE_UIELEMENT,                  "UIELEMENT",                   false, NULL},
    {GPUIMAGE_FILECONFIG,                 "FILE CONFIG",                 false, NULL},
    {GPUIMAGE_FILTERGROUP,                "FILTER GROUP",                false, NULL},
    {GPUIMAGE_FACES,                      "FACES",                       false, NULL},
    {GPUIMAGE_NUMFILTERS,                 "NUMFILTERS",                  false, NULL},
    {GPUIMAGE_END_FILTER,                 "",                            false, NULL}
};
